name: Add Stars

on: [watch]

jobs:
  addstars:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: add watcher to readme
      run: |
        echo -e "\nWe got a :star: from [@${{github.actor}}](https://github.com/${{github.actor}})" >> README.md 
    
    - name: Commit changes
      uses: elstudio/actions-js-build/commit@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUSH_BRANCH: 'master'

    
    
